import { generateStableId } from '@/utils/seededRandom';
import type { Account } from '@/types/account';

// Use a fixed base timestamp for deterministic dates
const BASE_TIME = new Date('2024-01-01T00:00:00Z').getTime();

/**
 * Generate dummy accounts with deterministic data
 * Each account is generated with stable IDs and fixed timestamps
 */
import { randomString } from '@/utils/seededRandom';

export function generateDummyAccounts(): Account[] {
  return [
    generateAccount0(),
    generateAccount1(),
    generateAccount2(),
    generateAccount3(),
    generateAccount4(),
    generateAccount5(),
    generateAccount6(),
    generateAccount7(),
  ];
}

function generateAccount0(): Account {
  return {
    id: generateStableId('account', 0),
    name: 'Binance Main',
    exchange: 'Binance',
    availableMarkets: {
      BN_SPOT: ['BTC_USDT', 'ETH_USDT', 'BNB_USDT', 'SOL_USDT', 'XRP_USDT', 'ADA_USDT'],
      BN_USDS_M: ['BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT', 'ADAUSDT', 'DOGEUSDT'],
    },
    apiKey: randomString(64),
    balanceInformation: {
      BN_SPOT: [
        { symbol: 'USDT', balance: 10000, available: 9500, inOrder: 500 },
        { symbol: 'BTC', balance: 0.5, available: 0.45, inOrder: 0.05 },
        { symbol: 'ETH', balance: 2.5, available: 2.3, inOrder: 0.2 },
        { symbol: 'BNB', balance: 15, available: 15, inOrder: 0 },
      ],
      BN_USDS_M: [
        { symbol: 'USDT', balance: 25000, available: 18500, inOrder: 6500 },
        { symbol: 'USDC', balance: 5000, available: 5000, inOrder: 0 },
      ],
    },
    positionInformation: {
      BN_USDS_M: [
        {
          symbol: 'BTCUSDT',
          side: 'long',
          quantity: 0.15,
          averagePrice: 48500,
          liquidationPrice: 43650,
          entryPrice: 48500,
          leverage: 10,
          unrealizedPnl: 225,
          realizedPnl: 125,
          markPrice: 50000,
          positionInitialMargin: 727.5,
          positionMaintenanceMargin: 72.75,
        },
        {
          symbol: 'ETHUSDT',
          side: 'long',
          quantity: 3,
          averagePrice: 2950,
          liquidationPrice: 2655,
          entryPrice: 2950,
          leverage: 10,
          unrealizedPnl: 450,
          realizedPnl: 0,
          markPrice: 3100,
          positionInitialMargin: 885,
          positionMaintenanceMargin: 88.5,
        },
        {
          symbol: 'SOLUSDT',
          side: 'short',
          quantity: 20,
          averagePrice: 120,
          liquidationPrice: 132,
          entryPrice: 120,
          leverage: 10,
          unrealizedPnl: 200,
          realizedPnl: 0,
          markPrice: 110,
          positionInitialMargin: 240,
          positionMaintenanceMargin: 24,
        },
      ],
    },
    openOrders: {
      BN_SPOT: [
        {
          id: generateStableId('account-0-order', 0),
          symbol: 'BTC_USDT',
          market: 'BN_SPOT',
          side: 'buy',
          type: 'limit',
          status: 'open',
          quantity: 0.05,
          filledQuantity: 0,
          price: 48000,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 2,
          updatedAt: BASE_TIME - 3600000 * 2,
        },
        {
          id: generateStableId('account-0-order', 1),
          symbol: 'ETH_USDT',
          market: 'BN_SPOT',
          side: 'buy',
          type: 'limit',
          status: 'open',
          quantity: 0.2,
          filledQuantity: 0,
          price: 2900,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 3,
          updatedAt: BASE_TIME - 3600000 * 3,
        },
        {
          id: generateStableId('account-0-order', 2),
          symbol: 'SOL_USDT',
          market: 'BN_SPOT',
          side: 'sell',
          type: 'limit',
          status: 'partially_filled',
          quantity: 10,
          filledQuantity: 3,
          price: 125,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 5,
          updatedAt: BASE_TIME - 3600000 * 1,
        },
      ],
      BN_USDS_M: [
        {
          id: generateStableId('account-0-order', 3),
          symbol: 'BTCUSDT',
          market: 'BN_USDS_M',
          side: 'sell',
          type: 'stop_loss',
          status: 'open',
          quantity: 0.15,
          filledQuantity: 0,
          price: 47000,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000,
          updatedAt: BASE_TIME - 3600000,
        },
        {
          id: generateStableId('account-0-order', 4),
          symbol: 'BTCUSDT',
          market: 'BN_USDS_M',
          side: 'sell',
          type: 'take_profit',
          status: 'open',
          quantity: 0.15,
          filledQuantity: 0,
          price: 52000,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000,
          updatedAt: BASE_TIME - 3600000,
        },
        {
          id: generateStableId('account-0-order', 5),
          symbol: 'XRPUSDT',
          market: 'BN_USDS_M',
          side: 'buy',
          type: 'limit',
          status: 'open',
          quantity: 1000,
          filledQuantity: 0,
          price: 0.5,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 7200000,
          updatedAt: BASE_TIME - 7200000,
        },
      ],
    },
    orderHistory: {
      BN_SPOT: [
        {
          id: generateStableId('account-0-order', 6),
          symbol: 'ETH_USDT',
          market: 'BN_SPOT',
          side: 'buy',
          type: 'market',
          status: 'filled',
          quantity: 0.5,
          filledQuantity: 0.5,
          averagePrice: 3050,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000 * 2,
          updatedAt: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-0-order', 7),
          symbol: 'BNB_USDT',
          market: 'BN_SPOT',
          side: 'buy',
          type: 'limit',
          status: 'filled',
          quantity: 5,
          filledQuantity: 5,
          price: 550,
          averagePrice: 550,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 86400000 * 3,
          updatedAt: BASE_TIME - 86400000 * 3,
        },
        {
          id: generateStableId('account-0-order', 8),
          symbol: 'SOL_USDT',
          market: 'BN_SPOT',
          side: 'buy',
          type: 'market',
          status: 'filled',
          quantity: 15,
          filledQuantity: 15,
          averagePrice: 108,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000 * 4,
          updatedAt: BASE_TIME - 86400000 * 4,
        },
        {
          id: generateStableId('account-0-order', 9),
          symbol: 'XRP_USDT',
          market: 'BN_SPOT',
          side: 'sell',
          type: 'limit',
          status: 'cancelled',
          quantity: 500,
          filledQuantity: 0,
          price: 0.65,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 86400000 * 5,
          updatedAt: BASE_TIME - 86400000 * 5,
        },
      ],
      BN_USDS_M: [
        {
          id: generateStableId('account-0-order', 10),
          symbol: 'BTCUSDT',
          market: 'BN_USDS_M',
          side: 'buy',
          type: 'market',
          status: 'filled',
          quantity: 0.15,
          filledQuantity: 0.15,
          averagePrice: 48500,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000,
          updatedAt: BASE_TIME - 86400000,
        },
        {
          id: generateStableId('account-0-order', 11),
          symbol: 'ETHUSDT',
          market: 'BN_USDS_M',
          side: 'buy',
          type: 'limit',
          status: 'filled',
          quantity: 3,
          filledQuantity: 3,
          price: 2950,
          averagePrice: 2950,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 86400000 * 2,
          updatedAt: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-0-order', 12),
          symbol: 'SOLUSDT',
          market: 'BN_USDS_M',
          side: 'sell',
          type: 'market',
          status: 'filled',
          quantity: 20,
          filledQuantity: 20,
          averagePrice: 120,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000 * 1.5,
          updatedAt: BASE_TIME - 86400000 * 1.5,
        },
      ],
    },
    positionHistory: {
      BN_USDS_M: [
        {
          id: generateStableId('account-0-position', 0),
          symbol: 'BTCUSDT',
          market: 'BN_USDS_M',
          side: 'long',
          quantity: 0.2,
          entryPrice: 42000,
          exitPrice: 44000,
          realizedPnl: 400,
          leverage: 10,
          openedAt: BASE_TIME - 86400000 * 15,
          closedAt: BASE_TIME - 86400000 * 10,
        },
        {
          id: generateStableId('account-0-position', 1),
          symbol: 'ETHUSDT',
          market: 'BN_USDS_M',
          side: 'short',
          quantity: 5,
          entryPrice: 3200,
          exitPrice: 3100,
          realizedPnl: 500,
          leverage: 5,
          openedAt: BASE_TIME - 86400000 * 7,
          closedAt: BASE_TIME - 86400000 * 3,
        },
        {
          id: generateStableId('account-0-position', 2),
          symbol: 'BNBUSDT',
          market: 'BN_USDS_M',
          side: 'long',
          quantity: 10,
          entryPrice: 520,
          exitPrice: 545,
          realizedPnl: 250,
          leverage: 15,
          openedAt: BASE_TIME - 86400000 * 20,
          closedAt: BASE_TIME - 86400000 * 18,
        },
        {
          id: generateStableId('account-0-position', 3),
          symbol: 'ADAUSDT',
          market: 'BN_USDS_M',
          side: 'short',
          quantity: 2000,
          entryPrice: 0.48,
          exitPrice: 0.45,
          realizedPnl: 60,
          leverage: 8,
          openedAt: BASE_TIME - 86400000 * 12,
          closedAt: BASE_TIME - 86400000 * 11,
        },
      ],
    },
    transactionHistory: {
      BN_SPOT: [
        {
          id: generateStableId('account-0-transaction', 0),
          type: 'trade',
          symbol: 'ETH_USDT',
          market: 'BN_SPOT',
          amount: -1525,
          coin: 'USDT',
          side: 'buy',
          price: 3050,
          quantity: 0.5,
          description: 'Market buy ETH/USDT',
          timestamp: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-0-transaction', 1),
          type: 'fee',
          symbol: 'ETH_USDT',
          market: 'BN_SPOT',
          amount: -1.525,
          coin: 'USDT',
          description: 'Trading fee (0.1%)',
          timestamp: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-0-transaction', 2),
          type: 'trade',
          symbol: 'BNB_USDT',
          market: 'BN_SPOT',
          amount: -2750,
          coin: 'USDT',
          side: 'buy',
          price: 550,
          quantity: 5,
          description: 'Limit buy BNB/USDT',
          timestamp: BASE_TIME - 86400000 * 3,
        },
        {
          id: generateStableId('account-0-transaction', 3),
          type: 'fee',
          symbol: 'BNB_USDT',
          market: 'BN_SPOT',
          amount: -0.005,
          coin: 'BNB',
          description: 'Trading fee paid in BNB (0.075%)',
          timestamp: BASE_TIME - 86400000 * 3,
        },
        {
          id: generateStableId('account-0-transaction', 4),
          type: 'trade',
          symbol: 'SOL_USDT',
          market: 'BN_SPOT',
          amount: 375,
          coin: 'USDT',
          side: 'sell',
          price: 125,
          quantity: 3,
          description: 'Partial fill SOL/USDT',
          timestamp: BASE_TIME - 3600000,
        },
      ],
      BN_USDS_M: [
        {
          id: generateStableId('account-0-transaction', 5),
          type: 'funding',
          symbol: 'BTCUSDT',
          market: 'BN_USDS_M',
          amount: -2.5,
          coin: 'USDT',
          description: 'Funding rate payment (0.01%)',
          timestamp: BASE_TIME - 3600000 * 8,
        },
        {
          id: generateStableId('account-0-transaction', 6),
          type: 'funding',
          symbol: 'ETHUSDT',
          market: 'BN_USDS_M',
          amount: 1.8,
          coin: 'USDT',
          description: 'Funding rate received (0.02%)',
          timestamp: BASE_TIME - 3600000 * 8,
        },
        {
          id: generateStableId('account-0-transaction', 7),
          type: 'trade',
          symbol: 'BTCUSDT',
          market: 'BN_USDS_M',
          amount: -7275,
          coin: 'USDT',
          side: 'buy',
          price: 48500,
          quantity: 0.15,
          description: 'Open long position BTCUSDT',
          timestamp: BASE_TIME - 86400000,
        },
        {
          id: generateStableId('account-0-transaction', 8),
          type: 'fee',
          symbol: 'BTCUSDT',
          market: 'BN_USDS_M',
          amount: -2.91,
          coin: 'USDT',
          description: 'Trading fee (0.04%)',
          timestamp: BASE_TIME - 86400000,
        },
        {
          id: generateStableId('account-0-transaction', 9),
          type: 'trade',
          symbol: 'ETHUSDT',
          market: 'BN_USDS_M',
          amount: -8850,
          coin: 'USDT',
          side: 'buy',
          price: 2950,
          quantity: 3,
          description: 'Open long position ETHUSDT',
          timestamp: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-0-transaction', 10),
          type: 'fee',
          symbol: 'ETHUSDT',
          market: 'BN_USDS_M',
          amount: -3.54,
          coin: 'USDT',
          description: 'Trading fee (0.04%)',
          timestamp: BASE_TIME - 86400000 * 2,
        },
      ],
    },
    isActive: true,
    createdAt: BASE_TIME - 86400000 * 30,
    updatedAt: BASE_TIME,
  };
}

function generateAccount1(): Account {
  return {
    id: generateStableId('account', 1),
    name: 'Binance Futures Pro',
    exchange: 'Binance',
    availableMarkets: {
      BN_USDS_M: [
        'BTCUSDT',
        'ETHUSDT',
        'SOLUSDT',
        'BNBUSDT',
        'ADAUSDT',
        'XRPUSDT',
        'DOGEUSDT',
        'LTCUSDT',
      ],
      BN_COIN_M: ['BTCUSD_PERPETUAL', 'ETHUSD_PERPETUAL', 'BNBUSD_PERPETUAL', 'SOLUSD_PERPETUAL'],
    },
    apiKey: randomString(64),
    balanceInformation: {
      BN_USDS_M: [
        { symbol: 'USDT', balance: 35000, available: 28000, inOrder: 7000 },
        { symbol: 'USDC', balance: 8000, available: 7500, inOrder: 500 },
      ],
      BN_COIN_M: [
        { symbol: 'BTC', balance: 1.8, available: 1.5, inOrder: 0.3 },
        { symbol: 'ETH', balance: 12.5, available: 10.0, inOrder: 2.5 },
        { symbol: 'BNB', balance: 25, available: 20, inOrder: 5 },
      ],
    },
    positionInformation: {
      BN_USDS_M: [
        {
          symbol: 'BTCUSDT',
          side: 'long',
          quantity: 0.25,
          averagePrice: 49500,
          liquidationPrice: 44550,
          entryPrice: 49500,
          leverage: 10,
          unrealizedPnl: 125,
          realizedPnl: 450,
          markPrice: 50000,
          positionInitialMargin: 1237.5,
          positionMaintenanceMargin: 123.75,
        },
        {
          symbol: 'SOLUSDT',
          side: 'long',
          quantity: 75,
          averagePrice: 105,
          liquidationPrice: 84,
          entryPrice: 105,
          leverage: 20,
          unrealizedPnl: 750,
          realizedPnl: 200,
          markPrice: 115,
          positionInitialMargin: 393.75,
          positionMaintenanceMargin: 39.38,
        },
        {
          symbol: 'ADAUSDT',
          side: 'short',
          quantity: 3000,
          averagePrice: 0.52,
          liquidationPrice: 0.624,
          entryPrice: 0.52,
          leverage: 15,
          unrealizedPnl: 210,
          realizedPnl: 50,
          markPrice: 0.45,
          positionInitialMargin: 104,
          positionMaintenanceMargin: 10.4,
        },
        {
          symbol: 'DOGEUSDT',
          side: 'long',
          quantity: 5000,
          averagePrice: 0.08,
          liquidationPrice: 0.064,
          entryPrice: 0.08,
          leverage: 20,
          unrealizedPnl: 50,
          realizedPnl: 0,
          markPrice: 0.09,
          positionInitialMargin: 20,
          positionMaintenanceMargin: 2,
        },
      ],
      BN_COIN_M: [
        {
          symbol: 'ETHUSD_PERPETUAL',
          side: 'long',
          quantity: 200,
          averagePrice: 3000,
          liquidationPrice: 2700,
          entryPrice: 3000,
          leverage: 10,
          unrealizedPnl: 0.1,
          realizedPnl: 0.05,
          markPrice: 3150,
          positionInitialMargin: 0.067,
          positionMaintenanceMargin: 0.0067,
        },
        {
          symbol: 'BTCUSD_PERPETUAL',
          side: 'short',
          quantity: 100,
          averagePrice: 50500,
          liquidationPrice: 55550,
          entryPrice: 50500,
          leverage: 10,
          unrealizedPnl: 0.01,
          realizedPnl: 0.02,
          markPrice: 50000,
          positionInitialMargin: 0.002,
          positionMaintenanceMargin: 0.0002,
        },
      ],
    },
    openOrders: {
      BN_USDS_M: [
        {
          id: generateStableId('account-1-order', 0),
          symbol: 'BNBUSDT',
          market: 'BN_USDS_M',
          side: 'buy',
          type: 'limit',
          status: 'open',
          quantity: 8,
          filledQuantity: 0,
          price: 520,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 4,
          updatedAt: BASE_TIME - 3600000 * 4,
        },
        {
          id: generateStableId('account-1-order', 1),
          symbol: 'SOLUSDT',
          market: 'BN_USDS_M',
          side: 'sell',
          type: 'take_profit',
          status: 'open',
          quantity: 35,
          filledQuantity: 0,
          price: 125,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 2,
          updatedAt: BASE_TIME - 3600000 * 2,
        },
        {
          id: generateStableId('account-1-order', 2),
          symbol: 'LTCUSDT',
          market: 'BN_USDS_M',
          side: 'buy',
          type: 'limit',
          status: 'partially_filled',
          quantity: 20,
          filledQuantity: 8,
          price: 68,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 6,
          updatedAt: BASE_TIME - 3600000 * 1,
        },
        {
          id: generateStableId('account-1-order', 3),
          symbol: 'BTCUSDT',
          market: 'BN_USDS_M',
          side: 'sell',
          type: 'stop_loss',
          status: 'open',
          quantity: 0.25,
          filledQuantity: 0,
          price: 48000,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000,
          updatedAt: BASE_TIME - 3600000,
        },
      ],
      BN_COIN_M: [
        {
          id: generateStableId('account-1-order', 4),
          symbol: 'SOLUSD_PERPETUAL',
          market: 'BN_COIN_M',
          side: 'buy',
          type: 'limit',
          status: 'open',
          quantity: 50,
          filledQuantity: 0,
          price: 100,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 3,
          updatedAt: BASE_TIME - 3600000 * 3,
        },
      ],
    },
    orderHistory: {
      BN_USDS_M: [
        {
          id: generateStableId('account-1-order', 2),
          symbol: 'SOLUSDT',
          market: 'BN_USDS_M',
          side: 'buy',
          type: 'market',
          status: 'filled',
          quantity: 50,
          filledQuantity: 50,
          averagePrice: 100,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000 * 3,
          updatedAt: BASE_TIME - 86400000 * 3,
        },
        {
          id: generateStableId('account-1-order', 3),
          symbol: 'ADAUSDT',
          market: 'BN_USDS_M',
          side: 'sell',
          type: 'limit',
          status: 'filled',
          quantity: 1000,
          filledQuantity: 1000,
          price: 0.5,
          averagePrice: 0.5,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 86400000 * 2,
          updatedAt: BASE_TIME - 86400000 * 2,
        },
      ],
    },
    positionHistory: {
      BN_USDS_M: [
        {
          id: generateStableId('account-1-position', 0),
          symbol: 'BTCUSDT',
          market: 'BN_USDS_M',
          side: 'long',
          quantity: 0.5,
          entryPrice: 40000,
          exitPrice: 45000,
          realizedPnl: 2500,
          leverage: 10,
          openedAt: BASE_TIME - 86400000 * 20,
          closedAt: BASE_TIME - 86400000 * 15,
        },
        {
          id: generateStableId('account-1-position', 1),
          symbol: 'ETHUSDT',
          market: 'BN_USDS_M',
          side: 'short',
          quantity: 10,
          entryPrice: 3500,
          exitPrice: 3200,
          realizedPnl: 3000,
          leverage: 15,
          openedAt: BASE_TIME - 86400000 * 10,
          closedAt: BASE_TIME - 86400000 * 5,
        },
      ],
    },
    transactionHistory: {
      BN_USDS_M: [
        {
          id: generateStableId('account-1-transaction', 0),
          type: 'trade',
          symbol: 'SOLUSDT',
          market: 'BN_USDS_M',
          amount: 5000,
          coin: 'USDT',
          side: 'buy',
          price: 100,
          quantity: 50,
          description: 'Market buy SOL futures',
          timestamp: BASE_TIME - 86400000 * 3,
        },
        {
          id: generateStableId('account-1-transaction', 1),
          type: 'funding',
          symbol: 'BTCUSDT',
          market: 'BN_USDS_M',
          amount: -12.5,
          coin: 'USDT',
          description: 'Funding rate payment',
          timestamp: BASE_TIME - 3600000 * 8,
        },
        {
          id: generateStableId('account-1-transaction', 2),
          type: 'fee',
          symbol: 'ADAUSDT',
          market: 'BN_USDS_M',
          amount: 0.5,
          coin: 'USDT',
          description: 'Trading fee',
          timestamp: BASE_TIME - 86400000 * 2,
        },
      ],
    },
    isActive: true,
    createdAt: BASE_TIME - 86400000 * 60,
    updatedAt: BASE_TIME - 86400000 * 2,
  };
}

// Continue with other accounts...
function generateAccount2(): Account {
  return {
    id: generateStableId('account', 2),
    name: 'Bybit Spot Trading',
    exchange: 'Bybit',
    availableMarkets: {
      BB_SPOT: ['BTC_USDT', 'ETH_USDT', 'SOL_USDT', 'XRP_USDT', 'DOGE_USDT'],
      BB_USDT_PERP: ['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'XRPUSDT', 'DOGEUSDT'],
    },
    apiKey: randomString(64),
    secretKey: randomString(64),
    balanceInformation: {
      BB_SPOT: [
        { symbol: 'USDT', balance: 20000, available: 18000, inOrder: 2000 },
        { symbol: 'BTC', balance: 0.35, available: 0.3, inOrder: 0.05 },
        { symbol: 'ETH', balance: 5, available: 4.5, inOrder: 0.5 },
        { symbol: 'SOL', balance: 100, available: 90, inOrder: 10 },
      ],
      BB_USDT_PERP: [{ symbol: 'USDT', balance: 15000, available: 12000, inOrder: 3000 }],
    },
    positionInformation: {
      BB_USDT_PERP: [
        {
          symbol: 'BTCUSDT',
          side: 'short',
          quantity: 0.1,
          averagePrice: 51000,
          liquidationPrice: 56100,
          entryPrice: 51000,
          leverage: 10,
          unrealizedPnl: 100,
          realizedPnl: 0,
          markPrice: 50000,
          positionInitialMargin: 510,
          positionMaintenanceMargin: 51,
        },
        {
          symbol: 'ETHUSDT',
          side: 'long',
          quantity: 2,
          averagePrice: 3000,
          liquidationPrice: 2700,
          entryPrice: 3000,
          leverage: 10,
          unrealizedPnl: 200,
          realizedPnl: 50,
          markPrice: 3100,
          positionInitialMargin: 600,
          positionMaintenanceMargin: 60,
        },
      ],
    },
    openOrders: {
      BB_SPOT: [
        {
          id: generateStableId('account-2-order', 0),
          symbol: 'BTC_USDT',
          market: 'BB_SPOT',
          side: 'buy',
          type: 'limit',
          status: 'open',
          quantity: 0.02,
          filledQuantity: 0,
          price: 47500,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 5,
          updatedAt: BASE_TIME - 3600000 * 5,
        },
        {
          id: generateStableId('account-2-order', 1),
          symbol: 'SOL_USDT',
          market: 'BB_SPOT',
          side: 'sell',
          type: 'limit',
          status: 'partially_filled',
          quantity: 10,
          filledQuantity: 3,
          price: 118,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 3,
          updatedAt: BASE_TIME - 3600000,
        },
      ],
      BB_USDT_PERP: [
        {
          id: generateStableId('account-2-order', 2),
          symbol: 'SOLUSDT',
          market: 'BB_USDT_PERP',
          side: 'buy',
          type: 'limit',
          status: 'open',
          quantity: 30,
          filledQuantity: 0,
          price: 105,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 2,
          updatedAt: BASE_TIME - 3600000 * 2,
        },
      ],
    },
    orderHistory: {
      BB_SPOT: [
        {
          id: generateStableId('account-2-order', 3),
          symbol: 'ETH_USDT',
          market: 'BB_SPOT',
          side: 'buy',
          type: 'market',
          status: 'filled',
          quantity: 1,
          filledQuantity: 1,
          averagePrice: 3020,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000 * 2,
          updatedAt: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-2-order', 4),
          symbol: 'XRP_USDT',
          market: 'BB_SPOT',
          side: 'buy',
          type: 'limit',
          status: 'filled',
          quantity: 1000,
          filledQuantity: 1000,
          price: 0.55,
          averagePrice: 0.55,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 86400000 * 4,
          updatedAt: BASE_TIME - 86400000 * 4,
        },
        {
          id: generateStableId('account-2-order', 5),
          symbol: 'DOGE_USDT',
          market: 'BB_SPOT',
          side: 'sell',
          type: 'market',
          status: 'filled',
          quantity: 5000,
          filledQuantity: 5000,
          averagePrice: 0.085,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000 * 3,
          updatedAt: BASE_TIME - 86400000 * 3,
        },
      ],
      BB_USDT_PERP: [
        {
          id: generateStableId('account-2-order', 6),
          symbol: 'BTCUSDT',
          market: 'BB_USDT_PERP',
          side: 'sell',
          type: 'market',
          status: 'filled',
          quantity: 0.1,
          filledQuantity: 0.1,
          averagePrice: 51000,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000,
          updatedAt: BASE_TIME - 86400000,
        },
        {
          id: generateStableId('account-2-order', 7),
          symbol: 'ETHUSDT',
          market: 'BB_USDT_PERP',
          side: 'buy',
          type: 'limit',
          status: 'filled',
          quantity: 2,
          filledQuantity: 2,
          price: 3000,
          averagePrice: 3000,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 86400000 * 1.5,
          updatedAt: BASE_TIME - 86400000 * 1.5,
        },
      ],
    },
    positionHistory: {
      BB_USDT_PERP: [
        {
          id: generateStableId('account-2-position', 0),
          symbol: 'SOLUSDT',
          market: 'BB_USDT_PERP',
          side: 'long',
          quantity: 50,
          entryPrice: 95,
          exitPrice: 110,
          realizedPnl: 750,
          leverage: 15,
          openedAt: BASE_TIME - 86400000 * 10,
          closedAt: BASE_TIME - 86400000 * 5,
        },
        {
          id: generateStableId('account-2-position', 1),
          symbol: 'XRPUSDT',
          market: 'BB_USDT_PERP',
          side: 'short',
          quantity: 2000,
          entryPrice: 0.6,
          exitPrice: 0.55,
          realizedPnl: 100,
          leverage: 10,
          openedAt: BASE_TIME - 86400000 * 8,
          closedAt: BASE_TIME - 86400000 * 6,
        },
      ],
    },
    transactionHistory: {
      BB_SPOT: [
        {
          id: generateStableId('account-2-transaction', 0),
          type: 'trade',
          symbol: 'ETH_USDT',
          market: 'BB_SPOT',
          amount: -3020,
          coin: 'USDT',
          side: 'buy',
          price: 3020,
          quantity: 1,
          description: 'Market buy ETH/USDT',
          timestamp: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-2-transaction', 1),
          type: 'fee',
          symbol: 'ETH_USDT',
          market: 'BB_SPOT',
          amount: -3.02,
          coin: 'USDT',
          description: 'Trading fee (0.1%)',
          timestamp: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-2-transaction', 2),
          type: 'trade',
          symbol: 'DOGE_USDT',
          market: 'BB_SPOT',
          amount: 425,
          coin: 'USDT',
          side: 'sell',
          price: 0.085,
          quantity: 5000,
          description: 'Market sell DOGE/USDT',
          timestamp: BASE_TIME - 86400000 * 3,
        },
      ],
      BB_USDT_PERP: [
        {
          id: generateStableId('account-2-transaction', 3),
          type: 'funding',
          symbol: 'BTCUSDT',
          market: 'BB_USDT_PERP',
          amount: 1.5,
          coin: 'USDT',
          description: 'Funding rate received (0.01%)',
          timestamp: BASE_TIME - 3600000 * 8,
        },
        {
          id: generateStableId('account-2-transaction', 4),
          type: 'trade',
          symbol: 'ETHUSDT',
          market: 'BB_USDT_PERP',
          amount: -6000,
          coin: 'USDT',
          side: 'buy',
          price: 3000,
          quantity: 2,
          description: 'Open long position ETHUSDT',
          timestamp: BASE_TIME - 86400000 * 1.5,
        },
      ],
    },
    isActive: true,
    createdAt: BASE_TIME - 86400000 * 25,
    updatedAt: BASE_TIME - 3600000,
  };
}

function generateAccount3(): Account {
  return {
    id: generateStableId('account', 3),
    name: 'Bybit Derivatives',
    exchange: 'Bybit',
    availableMarkets: {
      BB_USDT_PERP: ['BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'ADAUSDT', 'LTCUSDT'],
      BB_USDC_PERP: ['BTC-PERP', 'ETH-PERP', 'SOL-PERP'],
      BB_Perpetual: ['BTCUSD', 'ETHUSD', 'SOLUSD'],
    },
    apiKey: randomString(64),
    secretKey: randomString(64),
    balanceInformation: {
      BB_USDT_PERP: [{ symbol: 'USDT', balance: 50000, available: 35000, inOrder: 15000 }],
      BB_USDC_PERP: [{ symbol: 'USDC', balance: 20000, available: 15000, inOrder: 5000 }],
      BB_Perpetual: [
        { symbol: 'BTC', balance: 2, available: 1.5, inOrder: 0.5 },
        { symbol: 'ETH', balance: 15, available: 12, inOrder: 3 },
      ],
    },
    positionInformation: {
      BB_USDT_PERP: [
        {
          symbol: 'BTCUSDT',
          side: 'long',
          quantity: 0.3,
          averagePrice: 49000,
          liquidationPrice: 44100,
          entryPrice: 49000,
          leverage: 10,
          unrealizedPnl: 300,
          realizedPnl: 150,
          markPrice: 50000,
          positionInitialMargin: 1470,
          positionMaintenanceMargin: 147,
        },
        {
          symbol: 'BNBUSDT',
          side: 'short',
          quantity: 10,
          averagePrice: 560,
          liquidationPrice: 616,
          entryPrice: 560,
          leverage: 10,
          unrealizedPnl: 100,
          realizedPnl: 0,
          markPrice: 550,
          positionInitialMargin: 560,
          positionMaintenanceMargin: 56,
        },
        {
          symbol: 'LTCUSDT',
          side: 'long',
          quantity: 30,
          averagePrice: 70,
          liquidationPrice: 56,
          entryPrice: 70,
          leverage: 20,
          unrealizedPnl: 90,
          realizedPnl: 30,
          markPrice: 73,
          positionInitialMargin: 105,
          positionMaintenanceMargin: 10.5,
        },
      ],
      BB_USDC_PERP: [
        {
          symbol: 'ETH-PERP',
          side: 'long',
          quantity: 5,
          averagePrice: 3050,
          liquidationPrice: 2745,
          entryPrice: 3050,
          leverage: 10,
          unrealizedPnl: 250,
          realizedPnl: 100,
          markPrice: 3100,
          positionInitialMargin: 1525,
          positionMaintenanceMargin: 152.5,
        },
      ],
      BB_Perpetual: [
        {
          symbol: 'BTCUSD',
          side: 'short',
          quantity: 5000,
          averagePrice: 50500,
          liquidationPrice: 55550,
          entryPrice: 50500,
          leverage: 10,
          unrealizedPnl: 0.025,
          realizedPnl: 0.01,
          markPrice: 50000,
          positionInitialMargin: 0.099,
          positionMaintenanceMargin: 0.0099,
        },
      ],
    },
    openOrders: {
      BB_USDT_PERP: [
        {
          id: generateStableId('account-3-order', 0),
          symbol: 'BTCUSDT',
          market: 'BB_USDT_PERP',
          side: 'sell',
          type: 'take_profit',
          status: 'open',
          quantity: 0.15,
          filledQuantity: 0,
          price: 52000,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000,
          updatedAt: BASE_TIME - 3600000,
        },
        {
          id: generateStableId('account-3-order', 1),
          symbol: 'SOLUSDT',
          market: 'BB_USDT_PERP',
          side: 'buy',
          type: 'limit',
          status: 'open',
          quantity: 40,
          filledQuantity: 0,
          price: 108,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 4,
          updatedAt: BASE_TIME - 3600000 * 4,
        },
      ],
      BB_USDC_PERP: [
        {
          id: generateStableId('account-3-order', 2),
          symbol: 'BTC-PERP',
          market: 'BB_USDC_PERP',
          side: 'buy',
          type: 'limit',
          status: 'partially_filled',
          quantity: 0.1,
          filledQuantity: 0.03,
          price: 48500,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 3600000 * 6,
          updatedAt: BASE_TIME - 3600000 * 2,
        },
      ],
    },
    orderHistory: {
      BB_USDT_PERP: [
        {
          id: generateStableId('account-3-order', 3),
          symbol: 'BTCUSDT',
          market: 'BB_USDT_PERP',
          side: 'buy',
          type: 'market',
          status: 'filled',
          quantity: 0.3,
          filledQuantity: 0.3,
          averagePrice: 49000,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000 * 2,
          updatedAt: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-3-order', 4),
          symbol: 'BNBUSDT',
          market: 'BB_USDT_PERP',
          side: 'sell',
          type: 'limit',
          status: 'filled',
          quantity: 10,
          filledQuantity: 10,
          price: 560,
          averagePrice: 560,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 86400000 * 3,
          updatedAt: BASE_TIME - 86400000 * 3,
        },
        {
          id: generateStableId('account-3-order', 5),
          symbol: 'ADAUSDT',
          market: 'BB_USDT_PERP',
          side: 'buy',
          type: 'market',
          status: 'filled',
          quantity: 1500,
          filledQuantity: 1500,
          averagePrice: 0.47,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000 * 5,
          updatedAt: BASE_TIME - 86400000 * 5,
        },
        {
          id: generateStableId('account-3-order', 6),
          symbol: 'ADAUSDT',
          market: 'BB_USDT_PERP',
          side: 'sell',
          type: 'limit',
          status: 'filled',
          quantity: 1500,
          filledQuantity: 1500,
          price: 0.5,
          averagePrice: 0.5,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 86400000 * 4,
          updatedAt: BASE_TIME - 86400000 * 4,
        },
      ],
      BB_USDC_PERP: [
        {
          id: generateStableId('account-3-order', 7),
          symbol: 'ETH-PERP',
          market: 'BB_USDC_PERP',
          side: 'buy',
          type: 'limit',
          status: 'filled',
          quantity: 5,
          filledQuantity: 5,
          price: 3050,
          averagePrice: 3050,
          timeInForce: 'GTC',
          createdAt: BASE_TIME - 86400000 * 1.5,
          updatedAt: BASE_TIME - 86400000 * 1.5,
        },
      ],
      BB_Perpetual: [
        {
          id: generateStableId('account-3-order', 8),
          symbol: 'BTCUSD',
          market: 'BB_Perpetual',
          side: 'sell',
          type: 'market',
          status: 'filled',
          quantity: 5000,
          filledQuantity: 5000,
          averagePrice: 50500,
          timeInForce: 'IOC',
          createdAt: BASE_TIME - 86400000,
          updatedAt: BASE_TIME - 86400000,
        },
      ],
    },
    positionHistory: {
      BB_USDT_PERP: [
        {
          id: generateStableId('account-3-position', 0),
          symbol: 'ADAUSDT',
          market: 'BB_USDT_PERP',
          side: 'long',
          quantity: 1500,
          entryPrice: 0.47,
          exitPrice: 0.5,
          realizedPnl: 45,
          leverage: 12,
          openedAt: BASE_TIME - 86400000 * 5,
          closedAt: BASE_TIME - 86400000 * 4,
        },
        {
          id: generateStableId('account-3-position', 1),
          symbol: 'SOLUSDT',
          market: 'BB_USDT_PERP',
          side: 'short',
          quantity: 25,
          entryPrice: 115,
          exitPrice: 108,
          realizedPnl: 175,
          leverage: 15,
          openedAt: BASE_TIME - 86400000 * 12,
          closedAt: BASE_TIME - 86400000 * 8,
        },
        {
          id: generateStableId('account-3-position', 2),
          symbol: 'ETHUSDT',
          market: 'BB_USDT_PERP',
          side: 'long',
          quantity: 4,
          entryPrice: 2850,
          exitPrice: 2950,
          realizedPnl: 400,
          leverage: 8,
          openedAt: BASE_TIME - 86400000 * 15,
          closedAt: BASE_TIME - 86400000 * 10,
        },
      ],
      BB_USDC_PERP: [
        {
          id: generateStableId('account-3-position', 3),
          symbol: 'SOL-PERP',
          market: 'BB_USDC_PERP',
          side: 'long',
          quantity: 60,
          entryPrice: 98,
          exitPrice: 105,
          realizedPnl: 420,
          leverage: 10,
          openedAt: BASE_TIME - 86400000 * 7,
          closedAt: BASE_TIME - 86400000 * 5,
        },
      ],
    },
    transactionHistory: {
      BB_USDT_PERP: [
        {
          id: generateStableId('account-3-transaction', 0),
          type: 'trade',
          symbol: 'BTCUSDT',
          market: 'BB_USDT_PERP',
          amount: -14700,
          coin: 'USDT',
          side: 'buy',
          price: 49000,
          quantity: 0.3,
          description: 'Open long position BTCUSDT',
          timestamp: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-3-transaction', 1),
          type: 'fee',
          symbol: 'BTCUSDT',
          market: 'BB_USDT_PERP',
          amount: -5.88,
          coin: 'USDT',
          description: 'Trading fee (0.04%)',
          timestamp: BASE_TIME - 86400000 * 2,
        },
        {
          id: generateStableId('account-3-transaction', 2),
          type: 'funding',
          symbol: 'BTCUSDT',
          market: 'BB_USDT_PERP',
          amount: -3.5,
          coin: 'USDT',
          description: 'Funding rate payment (0.01%)',
          timestamp: BASE_TIME - 3600000 * 8,
        },
        {
          id: generateStableId('account-3-transaction', 3),
          type: 'funding',
          symbol: 'BNBUSDT',
          market: 'BB_USDT_PERP',
          amount: 2.8,
          coin: 'USDT',
          description: 'Funding rate received (0.05%)',
          timestamp: BASE_TIME - 3600000 * 8,
        },
      ],
      BB_USDC_PERP: [
        {
          id: generateStableId('account-3-transaction', 4),
          type: 'trade',
          symbol: 'ETH-PERP',
          market: 'BB_USDC_PERP',
          amount: -15250,
          coin: 'USDC',
          side: 'buy',
          price: 3050,
          quantity: 5,
          description: 'Open long position ETH-PERP',
          timestamp: BASE_TIME - 86400000 * 1.5,
        },
        {
          id: generateStableId('account-3-transaction', 5),
          type: 'fee',
          symbol: 'ETH-PERP',
          market: 'BB_USDC_PERP',
          amount: -6.1,
          coin: 'USDC',
          description: 'Trading fee (0.04%)',
          timestamp: BASE_TIME - 86400000 * 1.5,
        },
      ],
      BB_Perpetual: [
        {
          id: generateStableId('account-3-transaction', 6),
          type: 'trade',
          symbol: 'BTCUSD',
          market: 'BB_Perpetual',
          amount: -0.099,
          coin: 'BTC',
          side: 'sell',
          price: 50500,
          quantity: 5000,
          description: 'Open short position BTCUSD',
          timestamp: BASE_TIME - 86400000,
        },
        {
          id: generateStableId('account-3-transaction', 7),
          type: 'fee',
          symbol: 'BTCUSD',
          market: 'BB_Perpetual',
          amount: -0.00004,
          coin: 'BTC',
          description: 'Trading fee (0.04%)',
          timestamp: BASE_TIME - 86400000,
        },
      ],
    },
    isActive: true,
    createdAt: BASE_TIME - 86400000 * 20,
    updatedAt: BASE_TIME - 1800000,
  };
}

function generateAccount4(): Account {
  return {
    id: generateStableId('account', 4),
    name: 'High Frequency Trading',
    exchange: 'Binance',
    availableMarkets: {
      BN_SPOT: ['BTC_USDT', 'ETH_USDT', 'BNB_USDT', 'SOL_USDT', 'LINK_USDT', 'AVAX_USDT'],
      BN_USDS_M: ['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'LINKUSDT', 'AVAXUSDT'],
    },
    apiKey: randomString(64),
    balanceInformation: {
      BN_SPOT: [
        { symbol: 'USDT', balance: 100000, available: 75000, inOrder: 25000 },
        { symbol: 'BTC', balance: 1.5, available: 1.2, inOrder: 0.3 },
        { symbol: 'ETH', balance: 8, available: 6, inOrder: 2 },
      ],
      BN_USDS_M: [{ symbol: 'USDT', balance: 80000, available: 60000, inOrder: 20000 }],
    },
    positionInformation: {
      BN_USDS_M: [
        {
          symbol: 'BTCUSDT',
          side: 'long',
          quantity: 0.5,
          averagePrice: 49800,
          liquidationPrice: 39840,
          entryPrice: 49800,
          leverage: 25,
          unrealizedPnl: 100,
          realizedPnl: 2500,
          markPrice: 50000,
          positionInitialMargin: 996,
          positionMaintenanceMargin: 99.6,
        },
        {
          symbol: 'LINKUSDT',
          side: 'short',
          quantity: 500,
          averagePrice: 15,
          liquidationPrice: 16.5,
          entryPrice: 15,
          leverage: 10,
          unrealizedPnl: 250,
          realizedPnl: 100,
          markPrice: 14.5,
          positionInitialMargin: 750,
          positionMaintenanceMargin: 75,
        },
      ],
    },
    openOrders: {
      BN_SPOT: Array.from({ length: 8 }, (_, i) => ({
        id: generateStableId('account-4-order', i),
        symbol: (['BTC_USDT', 'ETH_USDT', 'BNB_USDT', 'SOL_USDT'] as const)[i % 4],
        market: 'BN_SPOT' as const,
        side: i % 2 === 0 ? ('buy' as const) : ('sell' as const),
        type: 'limit' as const,
        status: 'open' as const,
        quantity: [0.01, 0.1, 2, 10][i % 4],
        filledQuantity: 0,
        price: [49000, 3000, 540, 110][i % 4],
        timeInForce: 'GTC' as const,
        createdAt: BASE_TIME - 3600000 * (i + 1),
        updatedAt: BASE_TIME - 3600000 * (i + 1),
      })),
    },
    orderHistory: {
      BN_SPOT: Array.from({ length: 20 }, (_, i) => ({
        id: generateStableId('account-4-order-hist', i),
        symbol: (['BTC_USDT', 'ETH_USDT', 'SOL_USDT', 'BNB_USDT', 'LINK_USDT'] as const)[i % 5],
        market: 'BN_SPOT' as const,
        side: i % 2 === 0 ? ('buy' as const) : ('sell' as const),
        type: i % 3 === 0 ? ('market' as const) : ('limit' as const),
        status: 'filled' as const,
        quantity: [0.02, 0.5, 5, 3, 20][i % 5],
        filledQuantity: [0.02, 0.5, 5, 3, 20][i % 5],
        price: i % 3 === 0 ? undefined : [49500, 3050, 112, 545, 14.8][i % 5],
        averagePrice: [49500, 3050, 112, 545, 14.8][i % 5],
        timeInForce: i % 3 === 0 ? ('IOC' as const) : ('GTC' as const),
        createdAt: BASE_TIME - 86400000 * (i / 4 + 0.5),
        updatedAt: BASE_TIME - 86400000 * (i / 4 + 0.5),
      })),
    },
    positionHistory: {
      BN_USDS_M: Array.from({ length: 10 }, (_, i) => ({
        id: generateStableId('account-4-position', i),
        symbol: (['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'LINKUSDT', 'AVAXUSDT'] as const)[i % 5],
        market: 'BN_USDS_M' as const,
        side: i % 2 === 0 ? ('long' as const) : ('short' as const),
        quantity: [0.1, 2, 20, 50, 10][i % 5],
        entryPrice: [48000, 2900, 105, 14, 35][i % 5],
        exitPrice: [49000, 3000, 110, 13.5, 37][i % 5],
        realizedPnl: [100, 200, 100, 25, 20][i % 5] * (i % 2 === 0 ? 1 : -1),
        leverage: [10, 15, 20, 25, 30][i % 5],
        openedAt: BASE_TIME - 86400000 * (20 - i * 2),
        closedAt: BASE_TIME - 86400000 * (19 - i * 2),
      })),
    },
    transactionHistory: {
      BN_SPOT: Array.from({ length: 15 }, (_, i) => ({
        id: generateStableId('account-4-transaction', i),
        type: i % 3 === 2 ? ('fee' as const) : ('trade' as const),
        symbol: (['BTC_USDT', 'ETH_USDT', 'SOL_USDT'] as const)[i % 3],
        market: 'BN_SPOT' as const,
        amount:
          i % 3 === 2 ? -[49.5, 3.05, 0.112][i % 3] : -[4950, 1525, 560][Math.floor(i / 3) % 3],
        coin: 'USDT' as const,
        side: i % 3 !== 2 ? (i % 2 === 0 ? ('buy' as const) : ('sell' as const)) : undefined,
        price: i % 3 !== 2 ? [49500, 3050, 112][i % 3] : undefined,
        quantity: i % 3 !== 2 ? [0.1, 0.5, 5][i % 3] : undefined,
        description: i % 3 === 2 ? 'Trading fee (0.1%)' : `HFT trade ${i}`,
        timestamp: BASE_TIME - 3600000 * (i * 2),
      })),
    },
    isActive: true,
    createdAt: BASE_TIME - 86400000 * 90,
    updatedAt: BASE_TIME - 600000,
  };
}

function generateAccount5(): Account {
  return {
    id: generateStableId('account', 5),
    name: 'Swing Trading Portfolio',
    exchange: 'Bybit',
    availableMarkets: {
      BB_SPOT: ['BTC_USDT', 'ETH_USDT', 'XRP_USDT', 'ADA_USDT', 'DOGE_USDT'],
      BB_USDT_PERP: ['BTCUSDT', 'ETHUSDT', 'XRPUSDT', 'ADAUSDT'],
    },
    apiKey: randomString(64),
    secretKey: randomString(64),
    balanceInformation: {
      BB_SPOT: [
        { symbol: 'USDT', balance: 30000, available: 22000, inOrder: 8000 },
        { symbol: 'BTC', balance: 0.25, available: 0.25, inOrder: 0 },
        { symbol: 'ETH', balance: 3, available: 2.5, inOrder: 0.5 },
        { symbol: 'XRP', balance: 5000, available: 4000, inOrder: 1000 },
      ],
      BB_USDT_PERP: [{ symbol: 'USDT', balance: 25000, available: 18000, inOrder: 7000 }],
    },
    positionInformation: {
      BB_USDT_PERP: [
        {
          symbol: 'XRPUSDT',
          side: 'long',
          quantity: 10000,
          averagePrice: 0.55,
          liquidationPrice: 0.44,
          entryPrice: 0.55,
          leverage: 20,
          unrealizedPnl: 500,
          realizedPnl: 200,
          markPrice: 0.6,
          positionInitialMargin: 275,
          positionMaintenanceMargin: 27.5,
        },
        {
          symbol: 'ADAUSDT',
          side: 'short',
          quantity: 5000,
          averagePrice: 0.48,
          liquidationPrice: 0.576,
          entryPrice: 0.48,
          leverage: 15,
          unrealizedPnl: 150,
          realizedPnl: 0,
          markPrice: 0.45,
          positionInitialMargin: 160,
          positionMaintenanceMargin: 16,
        },
      ],
    },
    openOrders: {
      BB_SPOT: Array.from({ length: 5 }, (_, i) => ({
        id: generateStableId('account-5-order', i),
        symbol: (['BTC_USDT', 'ETH_USDT', 'XRP_USDT', 'ADA_USDT', 'DOGE_USDT'] as const)[i],
        market: 'BB_SPOT' as const,
        side: i % 2 === 0 ? ('buy' as const) : ('sell' as const),
        type: (['limit', 'limit', 'stop_loss', 'take_profit', 'limit'] as const)[i],
        status: i === 2 ? ('partially_filled' as const) : ('open' as const),
        quantity: [0.02, 0.5, 1000, 2000, 10000][i],
        filledQuantity: i === 2 ? 300 : 0,
        price: [47000, 3200, 0.52, 0.5, 0.09][i],
        timeInForce: 'GTC' as const,
        createdAt: BASE_TIME - 86400000 * (i + 1),
        updatedAt: BASE_TIME - 86400000 * (i === 2 ? 0.5 : i + 1),
      })),
    },
    orderHistory: {
      BB_SPOT: Array.from({ length: 12 }, (_, i) => ({
        id: generateStableId('account-5-order-hist', i),
        symbol: (['BTC_USDT', 'ETH_USDT', 'XRP_USDT', 'ADA_USDT'] as const)[i % 4],
        market: 'BB_SPOT' as const,
        side: i % 2 === 0 ? ('buy' as const) : ('sell' as const),
        type: i % 3 === 0 ? ('market' as const) : ('limit' as const),
        status: i === 8 ? ('cancelled' as const) : ('filled' as const),
        quantity: [0.05, 1, 2000, 3000][i % 4],
        filledQuantity: i === 8 ? 0 : [0.05, 1, 2000, 3000][i % 4],
        price: i % 3 === 0 ? undefined : [48500, 3000, 0.56, 0.47][i % 4],
        averagePrice: i === 8 ? undefined : [48500, 3000, 0.56, 0.47][i % 4],
        timeInForce: i % 3 === 0 ? ('IOC' as const) : ('GTC' as const),
        createdAt: BASE_TIME - 86400000 * (10 - i),
        updatedAt: BASE_TIME - 86400000 * (10 - i),
      })),
    },
    positionHistory: {
      BB_USDT_PERP: Array.from({ length: 6 }, (_, i) => ({
        id: generateStableId('account-5-position', i),
        symbol: (['BTCUSDT', 'ETHUSDT', 'XRPUSDT', 'ADAUSDT'] as const)[i % 4],
        market: 'BB_USDT_PERP' as const,
        side: i % 2 === 0 ? ('long' as const) : ('short' as const),
        quantity: [0.2, 3, 8000, 4000][i % 4],
        entryPrice: [46000, 2800, 0.5, 0.45][i % 4],
        exitPrice: [48000, 2900, 0.55, 0.42][i % 4],
        realizedPnl: [400, 300, 400, 120][i % 4] * (i % 2 === 0 ? 1 : -0.8),
        leverage: [8, 10, 15, 12][i % 4],
        openedAt: BASE_TIME - 86400000 * (30 - i * 5),
        closedAt: BASE_TIME - 86400000 * (25 - i * 5),
      })),
    },
    transactionHistory: {
      BB_SPOT: Array.from({ length: 10 }, (_, i) => ({
        id: generateStableId('account-5-transaction', i),
        type: i % 4 === 3 ? ('fee' as const) : ('trade' as const),
        symbol: (['BTC_USDT', 'ETH_USDT', 'XRP_USDT'] as const)[i % 3],
        market: 'BB_SPOT' as const,
        amount:
          i % 4 === 3
            ? -[2.425, 1.5, 0.28][i % 3]
            : [2425, 1500, 280][Math.floor(i / 4) % 3] * (i % 2 === 0 ? -1 : 1),
        coin: 'USDT' as const,
        side: i % 4 !== 3 ? (i % 2 === 0 ? ('buy' as const) : ('sell' as const)) : undefined,
        price: i % 4 !== 3 ? [48500, 3000, 0.56][i % 3] : undefined,
        quantity: i % 4 !== 3 ? [0.05, 0.5, 500][i % 3] : undefined,
        description: i % 4 === 3 ? 'Trading fee (0.1%)' : `Swing trade ${i}`,
        timestamp: BASE_TIME - 86400000 * Math.floor(i / 2),
      })),
      BB_USDT_PERP: Array.from({ length: 5 }, (_, i) => ({
        id: generateStableId('account-5-transaction', 10 + i),
        type: i === 0 || i === 3 ? ('funding' as const) : ('trade' as const),
        symbol: (['XRPUSDT', 'ADAUSDT'] as const)[i % 2],
        market: 'BB_USDT_PERP' as const,
        amount: i === 0 || i === 3 ? [-2.75, 1.6][i % 2] : -[5500, 2400][i % 2],
        coin: 'USDT' as const,
        side: i !== 0 && i !== 3 ? (i % 2 === 0 ? ('buy' as const) : ('sell' as const)) : undefined,
        price: i !== 0 && i !== 3 ? [0.55, 0.48][i % 2] : undefined,
        quantity: i !== 0 && i !== 3 ? [10000, 5000][i % 2] : undefined,
        description: i === 0 || i === 3 ? 'Funding rate' : 'Position open',
        timestamp: BASE_TIME - 86400000 * (i + 1),
      })),
    },
    isActive: true,
    createdAt: BASE_TIME - 86400000 * 60,
    updatedAt: BASE_TIME - 3600000 * 2,
  };
}

function generateAccount6(): Account {
  return {
    id: generateStableId('account', 6),
    name: 'Arbitrage Bot',
    exchange: 'Binance',
    availableMarkets: {
      BN_SPOT: ['BTC_USDT', 'ETH_USDT', 'BNB_USDT'],
      BN_USDS_M: ['BTCUSDT', 'ETHUSDT', 'BNBUSDT'],
      BN_COIN_M: ['BTCUSD_PERPETUAL', 'ETHUSD_PERPETUAL'],
    },
    apiKey: randomString(64),
    balanceInformation: {
      BN_SPOT: [
        { symbol: 'USDT', balance: 50000, available: 45000, inOrder: 5000 },
        { symbol: 'BTC', balance: 0.8, available: 0.7, inOrder: 0.1 },
      ],
      BN_USDS_M: [{ symbol: 'USDT', balance: 50000, available: 40000, inOrder: 10000 }],
      BN_COIN_M: [{ symbol: 'BTC', balance: 1, available: 0.8, inOrder: 0.2 }],
    },
    positionInformation: {
      BN_USDS_M: [
        {
          symbol: 'BTCUSDT',
          side: 'long',
          quantity: 0.2,
          averagePrice: 49950,
          liquidationPrice: 44955,
          entryPrice: 49950,
          leverage: 10,
          unrealizedPnl: 10,
          realizedPnl: 850,
          markPrice: 50000,
          positionInitialMargin: 999,
          positionMaintenanceMargin: 99.9,
        },
      ],
      BN_COIN_M: [
        {
          symbol: 'BTCUSD_PERPETUAL',
          side: 'short',
          quantity: 10000,
          averagePrice: 50050,
          liquidationPrice: 55055,
          entryPrice: 50050,
          leverage: 10,
          unrealizedPnl: 0.01,
          realizedPnl: 0.085,
          markPrice: 50000,
          positionInitialMargin: 0.02,
          positionMaintenanceMargin: 0.002,
        },
      ],
    },
    openOrders: {
      BN_SPOT: Array.from({ length: 3 }, (_, i) => ({
        id: generateStableId('account-6-order', i),
        symbol: 'BTC_USDT' as const,
        market: 'BN_SPOT' as const,
        side: i % 2 === 0 ? ('buy' as const) : ('sell' as const),
        type: 'limit' as const,
        status: 'open' as const,
        quantity: 0.01,
        filledQuantity: 0,
        price: 49900 + i * 20,
        timeInForce: 'GTC' as const,
        createdAt: BASE_TIME - 60000 * (i + 1),
        updatedAt: BASE_TIME - 60000 * (i + 1),
      })),
    },
    orderHistory: {
      BN_SPOT: Array.from({ length: 30 }, (_, i) => ({
        id: generateStableId('account-6-order-hist', i),
        symbol: 'BTC_USDT' as const,
        market: 'BN_SPOT' as const,
        side: i % 2 === 0 ? ('buy' as const) : ('sell' as const),
        type: 'limit' as const,
        status: 'filled' as const,
        quantity: 0.01,
        filledQuantity: 0.01,
        price: 49800 + (i % 10) * 20,
        averagePrice: 49800 + (i % 10) * 20,
        timeInForce: 'IOC' as const,
        createdAt: BASE_TIME - 3600000 * (i / 10),
        updatedAt: BASE_TIME - 3600000 * (i / 10),
      })),
    },
    positionHistory: {
      BN_USDS_M: Array.from({ length: 15 }, (_, i) => ({
        id: generateStableId('account-6-position', i),
        symbol: 'BTCUSDT' as const,
        market: 'BN_USDS_M' as const,
        side: i % 2 === 0 ? ('long' as const) : ('short' as const),
        quantity: 0.1,
        entryPrice: 49000 + i * 100,
        exitPrice: 49000 + i * 100 + (i % 2 === 0 ? 50 : -50),
        realizedPnl: 5 * (i % 2 === 0 ? 1 : -1),
        leverage: 10,
        openedAt: BASE_TIME - 3600000 * (30 - i * 2),
        closedAt: BASE_TIME - 3600000 * (29 - i * 2),
      })),
    },
    transactionHistory: {
      BN_SPOT: Array.from({ length: 20 }, (_, i) => ({
        id: generateStableId('account-6-transaction', i),
        type: i % 5 === 4 ? ('fee' as const) : ('trade' as const),
        symbol: 'BTC_USDT' as const,
        market: 'BN_SPOT' as const,
        amount: i % 5 === 4 ? -0.498 : 498 * (i % 2 === 0 ? -1 : 1),
        coin: 'USDT' as const,
        side: i % 5 !== 4 ? (i % 2 === 0 ? ('buy' as const) : ('sell' as const)) : undefined,
        price: i % 5 !== 4 ? 49800 : undefined,
        quantity: i % 5 !== 4 ? 0.01 : undefined,
        description: i % 5 === 4 ? 'Arbitrage fee' : `Arbitrage trade ${i}`,
        timestamp: BASE_TIME - 600000 * i,
      })),
    },
    isActive: true,
    createdAt: BASE_TIME - 86400000 * 45,
    updatedAt: BASE_TIME - 60000,
  };
}

function generateAccount7(): Account {
  return {
    id: generateStableId('account', 7),
    name: 'DCA Strategy',
    exchange: 'Bybit',
    availableMarkets: {
      BB_SPOT: ['BTC_USDT', 'ETH_USDT', 'SOL_USDT', 'LINK_USDT'],
    },
    apiKey: randomString(64),
    secretKey: randomString(64),
    balanceInformation: {
      BB_SPOT: [
        { symbol: 'USDT', balance: 40000, available: 38000, inOrder: 2000 },
        { symbol: 'BTC', balance: 0.6, available: 0.6, inOrder: 0 },
        { symbol: 'ETH', balance: 4.5, available: 4.5, inOrder: 0 },
        { symbol: 'SOL', balance: 150, available: 150, inOrder: 0 },
        { symbol: 'LINK', balance: 200, available: 200, inOrder: 0 },
      ],
    },
    openOrders: {
      BB_SPOT: Array.from({ length: 4 }, (_, i) => ({
        id: generateStableId('account-7-order', i),
        symbol: (['BTC_USDT', 'ETH_USDT', 'SOL_USDT', 'LINK_USDT'] as const)[i],
        market: 'BB_SPOT' as const,
        side: 'buy' as const,
        type: 'limit' as const,
        status: 'open' as const,
        quantity: [0.01, 0.2, 5, 10][i],
        filledQuantity: 0,
        price: [48000, 2900, 105, 13.5][i],
        timeInForce: 'GTC' as const,
        createdAt: BASE_TIME - 86400000 * (i + 1),
        updatedAt: BASE_TIME - 86400000 * (i + 1),
      })),
    },
    orderHistory: {
      BB_SPOT: Array.from({ length: 50 }, (_, i) => ({
        id: generateStableId('account-7-order-hist', i),
        symbol: (['BTC_USDT', 'ETH_USDT', 'SOL_USDT', 'LINK_USDT'] as const)[i % 4],
        market: 'BB_SPOT' as const,
        side: 'buy' as const,
        type: 'market' as const,
        status: 'filled' as const,
        quantity: [0.01, 0.15, 3, 8][i % 4],
        filledQuantity: [0.01, 0.15, 3, 8][i % 4],
        averagePrice: [47000 + i * 100, 2800 + i * 10, 100 + i * 0.5, 13 + i * 0.1][i % 4],
        timeInForce: 'IOC' as const,
        createdAt: BASE_TIME - 86400000 * (50 - i),
        updatedAt: BASE_TIME - 86400000 * (50 - i),
      })),
    },
    transactionHistory: {
      BB_SPOT: Array.from({ length: 50 }, (_, i) => ({
        id: generateStableId('account-7-transaction', i),
        type: i % 10 === 9 ? ('fee' as const) : ('trade' as const),
        symbol: (['BTC_USDT', 'ETH_USDT', 'SOL_USDT', 'LINK_USDT'] as const)[i % 4],
        market: 'BB_SPOT' as const,
        amount: i % 10 === 9 ? -[4.7, 0.42, 0.3, 0.104][i % 4] : -[470, 420, 300, 104][i % 4],
        coin: 'USDT' as const,
        side: i % 10 !== 9 ? ('buy' as const) : undefined,
        price:
          i % 10 !== 9
            ? [47000 + i * 100, 2800 + i * 10, 100 + i * 0.5, 13 + i * 0.1][i % 4]
            : undefined,
        quantity: i % 10 !== 9 ? [0.01, 0.15, 3, 8][i % 4] : undefined,
        description: i % 10 === 9 ? 'DCA fee' : `DCA purchase #${Math.floor(i / 4) + 1}`,
        timestamp: BASE_TIME - 86400000 * (50 - i),
      })),
    },
    isActive: true,
    createdAt: BASE_TIME - 86400000 * 365,
    updatedAt: BASE_TIME - 86400000,
  };
}
