import type { TradingExchange, TradingMarket, TradingSymbol } from '@/types/account';

// cspell:disable
export const EXCHANGE_MARKETS: Record<TradingExchange, TradingMarket[]> = {
  Binance: ['BN_SPOT', 'BN_USDS_M', 'BN_COIN_M'],
  Bybit: ['BB_SPOT', 'BB_USDT_PERP', 'BB_USDC_PERP', 'BB_Perpetual'],
};

export const MARKET_SYMBOLS: Record<TradingMarket, TradingSymbol[]> = {
  BN_SPOT: [
    'BTCUSDT',
    'ETHUSDT',
    'BNBUSDT',
    'SOLUSDT',
    'LTCUSDT',
    'HYPEUSDT',
    'AVAXUSDT',
    'LINKUSDT',
    'XRPUSDT',
    'ADAUSDT',
    'DOGEUSDT',
  ],
  BN_USDS_M: [
    'BTCUSDT',
    'ETHUSDT',
    'BNBUSDT',
    'SOLUSDT',
    'LTCUSDT',
    'HYPEUSDT',
    'AVAXUSDT',
    'LINKUSDT',
    'XRPUSDT',
    'ADAUSDT',
    'DOGEUSDT',
  ],
  BN_COIN_M: [
    'BTCUSD_PERPETUAL',
    'ETHUSD_PERPETUAL',
    'BNBUSD_PERPETUAL',
    'SOLUSD_PERPETUAL',
    'LTCUSD_PERPETUAL',
    'HYPEUSD_PERPETUAL',
    'AVAXUSD_PERPETUAL',
    'LINKUSD_PERPETUAL',
    'XRPUSD_PERPETUAL',
    'ADAUSD_PERPETUAL',
    'DOGEUSD_PERPETUAL',
  ],
  BB_SPOT: [
    'BTC_USDT',
    'ETH_USDT',
    'BNB_USDT',
    'SOL_USDT',
    'LTC_USDT',
    'HYPE_USDT',
    'AVAX_USDT',
    'LINK_USDT',
    'XRP_USDT',
    'ADA_USDT',
    'DOGE_USDT',
  ],
  BB_USDT_PERP: [
    'BTCUSDT',
    'ETHUSDT',
    'BNBUSDT',
    'SOLUSDT',
    'LTCUSDT',
    'HYPEUSDT',
    'AVAXUSDT',
    'LINKUSDT',
    'XRPUSDT',
    'ADAUSDT',
    'DOGEUSDT',
  ],
  BB_USDC_PERP: [
    'BTC-PERP',
    'ETH-PERP',
    'BNB-PERP',
    'SOL-PERP',
    'LTC-PERP',
    'HYPE-PERP',
    'AVAX-PERP',
    'LINK-PERP',
    'XRP-PERP',
    'ADA-PERP',
    'DOGE-PERP',
  ],
  BB_Perpetual: [
    'BTCUSD',
    'ETHUSD',
    'BNBUSD',
    'SOLUSD',
    'LTCUSD',
    'HYPEUSD',
    'AVAXUSD',
    'LINKUSD',
    'XRPUSD',
    'ADAUSD',
    'DOGEUSD',
  ],
};

export const MARKET_LABELS: Record<TradingMarket, string> = {
  BN_SPOT: 'Binance Spot',
  BN_USDS_M: 'Binance USDⓈ-M Futures',
  BN_COIN_M: 'Binance COIN-M Futures',
  BB_SPOT: 'Bybit Spot',
  BB_USDT_PERP: 'Bybit USDT Perpetual',
  BB_USDC_PERP: 'Bybit USDC Perpetual',
  BB_Perpetual: 'Bybit Inverse Perpetual',
};
